<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $collection = $this->getCollection();
$collection->setOrder('created_date', 'DESC');?>
    <div id="top-content">
        <div class="testimonials-text">
            <h1><?php echo $this->__('Testimonials') ?></h1>
        </div>
        <?php echo $this->showButton(); ?>
    </div>
<?php if($collection->getSize()): ?>
    <div style="padding-top: 30px; margin: 0 auto">
    <?php foreach ($collection as $item): ?>
        <div class="hero">
            <?php echo $item['content']; ?>
        </div>
        <div id="customers-name">
            <?php $customer = Mage::getModel('customer/customer')->load($item['customer_id']); ?>
            <?php echo  $customer->getData('firstname') . ' ' . $customer->getData('lastname'); ?>
        </div>
    <?php endforeach; ?>
    </div>
    <div class="pagination">
    <?php echo $this->getPagerHtml(); ?>
    </div>
<?php else: ?>
    <br><p><?php echo $this->__('The collection is empty.'); ?></p>
<?php endif ?>
